### ISSUE TITLE
[できたら]bulletでn+1問題に引っかかるsourceを洗い出し

### ISSUE THREAD

**Issue by yutoJ** [yasuhisa1984/dive-23-10#102]
とりあえず入れてみて、改修可能箇所を明確化

**Comment by yasuhisa1984** [comment]
bullet導入して検証してみました。
下記が検出されたログです。

【質問一覧画面】
USE eager loading detected
  Question => [:user]
  Add to your finder: :includes => [:user]
  Question => [:tags]
  Add to your finder: :includes => [:tags]

【ユーザー詳細ページ】
  Answer => [:question]
  Add to your finder: :includes => [:question]`

アドバイス通りincludesするとエラーがなくなるっぽいです。

**Comment by yutoJ** [comment]
おお！検出方法教えていただきたいです！

あと、なおすissueもあげて欲しいです ^ ^

**Comment by yasuhisa1984** [comment]
以下のURLの設定しました。
http://www.techscore.com/blog/2012/12/25/rails%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E7%B4%B9%E4%BB%8B-n1%E5%95%8F%E9%A1%8C%E3%82%92%E6%A4%9C%E5%87%BA%E3%81%99%E3%82%8B%E3%80%8Cbullet%E3%80%8D/

試してみたら問題があるページに遷移すると、Javascriptのホップアップウィンドウで検知されるみたいです。issueもあげてみますね ^ ^。
