### ISSUE TITLE
画面を縮めるとviewのタイトルが隠れてしまう

### ISSUE THREAD

**Issue by yutoJ** [yasuhisa1984/dive-23-10#132]
いい改善案ないでしょうか？

<header>以下を下げる？

**Comment by sayao88** [comment]
ドロップダウンでメニューをまとめて、ある程度のブラウザ幅では折り返し発生しないようにしたらなんとかなるかなと思うのですがいかがでしょう（文字サイズのことなので起こる可能性ありますが）

名前を押すとメニュー開く感じで（achieveで実装したbootstrapのスタイルです）

名前↓
マイページ
お気に入り
ログアウト

**Comment by yutoJ** [comment]
賛成です！

**Comment by yutoJ** [comment]
drop downにはなるっぽいのですが、タイミングが遅いのか、note PCから半分ぐらい狭めた際は被っちゃいます

**Comment by yutoJ** [comment]
タイミング調整が可能？まだ、調査中です。

**Comment by yutoJ** [comment]
navigation内の項目が結構フル画面でいっぱいになってきたので、いくつかdoopdownで集約したら改善するかもですね

**Comment by sayao88** [comment]
タイトルが長いですよね・・　Dive-23-10だけにします？

**Comment by sayao88** [comment]
タイトルそのままで。
