### ISSUE TITLE
カーソルを合わせると ? がでる謎の文字列発見

### ISSUE THREAD

**Issue by yutoJ** [yasuhisa1984/dive-23-10#135]
![screen shot 2017-06-03 at 16 59 16](https://cloud.githubusercontent.com/assets/19489801/26751851/14f719c6-487e-11e7-8a8b-f86fa881d914.png)

何でしょうかこれ、、？

**Comment by sayao88** [comment]
気づかなかったです。CSSが効いてますね。
bootstrapのスタイルみたいです。
アクセシビリティ的なやつだと思います・・。

```
abbr[title],abbr[data-original-title] {
    cursor: help;
    border-bottom: 1px dotted #777
}
```

abbrタグについて
http://www.htmq.com/html5/abbr.shtml

```
<abbr>タグは、略語や頭字語であることを表す際に使用します。
title属性は様々な要素で使用できる汎用的な属性ですが、<abbr>にtitle属性を指定した場合には特別な意味を持ちます。 <abbr>のtitle属性には、略語や頭字語の正式な名称を指定します。 title属性を指定した場合、一般的なブラウザではマウスカーソルを乗せた際にツールチップとして表示されます。

略語や頭字語は必ず<abbr>～</abbr>で囲まなくてはならないということはありませんが、 読者になじみのない略語を使用する場合には、title属性を持つ<abbr>でマークアップするか、 その略語が最初に使われるテキストに正式な名称を含めておくことが推奨されています。
```

**Comment by sayao88** [comment]
そこまでタグ使ってないので勉強になりました＾＾；
とりあえずバグではないのでサイトの方針の問題かもしれません。

**Comment by yutoJ** [comment]
これって原因ってどれですか？

自分が新規質問画面を作った時はなかったのですが、いつのまにか出始めました

![screen shot 2017-06-03 at 17 34 43](https://cloud.githubusercontent.com/assets/19489801/26752094/0f07eac2-4883-11e7-91f0-005dde2562d8.png)

**Comment by 46158n** [comment]
simple_formの必須項目にはデフォルトで*がつくみたいですね
　https://github.com/plataformatec/simple_form
　　Required fields are marked with an * prepended to their labels.
simple_form導入したタイミングでしょうか・・？

試しにrequired: falseしてみたら*は消えました

**Comment by sayao88** [comment]
あ、これ私がモデルにバリデーション追加したタイミングで出てきたと思います。

**Comment by yutoJ** [comment]
defaultっぽいのでcloseしちゃいます
