### ISSUE TITLE
application.cssのyieldのparameterは適用されてないっぽい

### ISSUE THREAD

**Issue by yutoJ** [yasuhisa1984/dive-23-10#146]
#132 

の延長で

```
.yield {
  padding-top: 60px;
}
```
にたどり着きましたが、

![screen shot 2017-06-03 at 18 14 11 1](https://cloud.githubusercontent.com/assets/19489801/26752359/e1b5388a-4888-11e7-89cc-387a78468e75.png)

 適用されてないっぽい、なぜ？

**Comment by sayao88** [comment]
CSSの優先順位が低いからだと思います。
すでに下記を書いているので、こちらを編集してもらえればと思います（yieldとcontainerは一緒につけている状態）
※やりたいことと違ったらすみません

common.scss
```
header + .container {
    padding-top: 64px;
}
```

**Comment by sayao88** [comment]
あ、理解しました。。ナビゲーション被るときに下げるってことですね。
とりあえずドロップダウンでできるだけまとめてみます。

**Comment by yutoJ** [comment]
ありがとうございます！

質問ですが、

```
  <div class="yield container">
    <%= render partial: 'application/display_flash_message', flash: flash %>
    <%= yield %>
  <!-- /.container --></div>
```

現在こんな感じになってましたが、cssは

```
  <div class="yield container">
```

だと1番目より2番目のを適用しますか？

どうやって競合の優先度を付けているのでしょうか？

**Comment by sayao88** [comment]
基本的にはあとに書くスタイルが優先されるので、
クラスを`<div class="yield container">`とつけたとしても
CSS側で
``.container{ color: red}
.yield{color:blue}
```
のようになっていればスタイルはblueが優先されます。

上記の例外としてはclassとidだったらidにつけたスタイルが強いので、あとに書いてもidのスタイルが優先されたりします。

**Comment by sayao88** [comment]
あとは階層が深いと優先順位高いとか・・あります。

**Comment by yutoJ** [comment]
理解できました！

ありがとうございます！

**Comment by yutoJ** [comment]
本件、
#132 がcloseされたため、closeします！
