### ISSUE TITLE
「戻る」の戻る先を指定したい

### ISSUE THREAD

**Issue by sayao88** [yasuhisa1984/dive-23-10#155]
フォームのエラーなどでリロードしたあとに戻るボタンをおすと今のページに戻るので、
明示的にリンク先を決めたほうが良い気がします。

**Comment by yutoJ** [comment]
ここむずいっすね >_<

一種類に限定するのが厳しい感じです。
例えば質問詳細は、一覧からもランキングからも、ユーザー詳細からもいけちゃうので

でも確かにたまに戻るが気持ちよく動かないので、悩みますね,,,

**Comment by sayao88** [comment]
たしかに、、どこからでも来れるページはそうですよね・・
