### ISSUE TITLE
たまに0票状態で投票できなくなる

### ISSUE THREAD

**Issue by yutoJ** [yasuhisa1984/dive-23-10#159]
以下の画面はないと思いますが、たまに起こります。根深そうです >_<

![screen shot 2017-06-04 at 16 23 23](https://cloud.githubusercontent.com/assets/19489801/26759747/3e0e588c-4942-11e7-9718-60d33ad73ea4.png)

**Comment by 46158n** [comment]
他のユーザが+1して自分が-1した状態ではなく、自分が未投票の状態でこうなってますか？
ちょっといじっただけだと再現できなかったです;;

**Comment by yutoJ** [comment]
すみません、勘違いかもです、logicあってそうでした>_<
