### ISSUE TITLE
お気に入り画面作成

### ISSUE THREAD

**Issue by yasuhisa1984** [yasuhisa1984/dive-23-10#16]

**Comment by sayao88** [comment]
コンフリクト回避のためissues/#16ブランチにて待機。（viewのみpushずみ）
※いったんは最低限の表示（お気に入りにした質問タイトルと質問へのリンク）のみいれてます。

コンフリクトしない段階でfavorites_controllerに下記記述を加えてpush予定です。

```
  def index
    @favorites = current_user.favorites
  end
```
