### ISSUE TITLE
どんなtag機能を実装すべきかの検討

### ISSUE THREAD

**Issue by yutoJ** [yasuhisa1984/dive-23-10#30]
自分で自由にtagを作れる？あるいはこちらでtag項目を設けて選択できるようにする？
(後者はstack over flowのように言語毎のtagがあるイメージ)

個人的には後者、でも前者が便利そうなら前者もいい。今のところ後者

**Comment by sayao88** [comment]
私も後者（tag項目を設けて選択させる）がよいかなと思います。
（自由にtagを作れる場合は言葉が乱立する可能性があるので、それを防ぐ手だてが必要な気がしていて、機能が複雑になってしまうかなと思います。）

**Comment by yasuhisa1984** [comment]
自分も乱立するのを懸念して。後者が良いかなぁって思っていました。
ただ、実際のスタックオバーフローを観てみると、自由に作れていてもそれほど乱立していない現状を考慮すると前者でもいいように思えました。
もし簡単にスタックオバーフローのような（タグ予測候補　＋　新規にタグ作成）を実装できるgemがあるのであれば、自由に作れる派になりました。
難易度で決めたいです。

**Comment by yutoJ** [comment]
本件とりあえず、後者ですかね！
後者できれば前者もできると思われます！

本家はあまり作らないでと書いてありましたが前者でした！
