### ISSUE TITLE
ユーザー貢献度(vote)のmodelについて

### ISSUE THREAD

**Issue by yutoJ** [yasuhisa1984/dive-23-10#31]
もしかしたらvoteはtable化しないとだめかも、、

理由：voteをintegerにしてquestion, answer tableに持たせておくとあるuserがそのquestion, answerにvoteしたのか分からないので難解でもvoteできてしまう。1 voteしたらvote buttonはdisableとするためにやはりtable実装がいる？

```
vote
  - user_id
  - question_id
```

**Comment by sayao88** [comment]
なるほど、そうですね。voteテーブルがないと投票したuserがたどれないですね・・

**Comment by 46158n** [comment]
voteをuserとquestionの中間モデルにしてuserモデルに
votes.find_by(user_id: current_user.id)とか定義しておけば
ユーザが投票してるかどうかは判定できないですかね？
（DIVE16 followingメソッドの真似）
で、trueなら投票ボタンは非活性化させる感じ。

**Comment by yasuhisa1984** [comment]
そうですね。Voteテーブルを作って、Votes.find_by(user_id: current_user.id)を定義すれば、投票しているかどうか判定できそうですね。

**Comment by yutoJ** [comment]
vote table必要そうっすね。
answerのvoteとquestionのvoteを分けるか一緒にできるかはどうでしょうか？

```
vote_for_question
  - user_id
  - question_id
vote_for_answer
  - user_id
  - answer_id
```

か

```
vote
   - user_id
   - answer_id
   - question_id
```

後者でいけそうですかね？

**Comment by yasuhisa1984** [comment]
後者でいけそうですね。

**Comment by yutoJ** [comment]
後者で作ります！

**Comment by yutoJ** [comment]
#45 
とりあえずvote table作っときました。

```
vote
  - user_id
  - question_id
  - answer_id
```
has_manyはquestion, user とanswer modelにつけましたが、userには

```
has_many :votes
```
というように`, dependent: :destroy`

userにつけるとuserが退会したときにvoteが減ってしまうのは急に貢献度が下がってるするからよくないのかな
と思ったため、、でもuserが削除されるとanswer, questionは削除されるから、その流れでvoteも結局消えちゃうのかな、、、
この辺、どうすべきか保留にしちゃいました。

また、ユーザ詳細画面でanswer, questionからvote読んたことと、voteの実装がまだ検討中なので

answers, questions tableからvoteをremoveするのはやめときました。
