### ISSUE TITLE
stack over flowみたいなvote buttonのデザイン

### ISSUE THREAD

**Issue by yutoJ** [yasuhisa1984/dive-23-10#32]
どうやって作るか、あるいは作れそうな場合作ってほしい

**Comment by sayao88** [comment]
railsのajax機能使う感じですかね・・？
CSSで三角を作って・・押されたらclass付け替えで表示変更？

**Comment by yutoJ** [comment]
はい、実装は僕もそのイメージでした。

ちょっとこだわるならstack over flowの三角の形と配置をどううまくやるかですね。
自分はcssがちょっとまだ苦手なので、後回しにしちゃそうです、、

**Comment by 46158n** [comment]
Ajax化は別issueに出します
