### ISSUE TITLE
[できたら]質問, 回答はmarkdownでも記入できるようにしたい

### ISSUE THREAD

**Issue by yutoJ** [yasuhisa1984/dive-23-10#33]
http://qiita.com/hkengo/items/978ea1874cf7e07cdbfc
で行けそう。

**Comment by yasuhisa1984** [comment]
マークダウンできたらやりたいですね。

回答のフォームに近い？gemも探してみました。
https://github.com/hughevans/pagedown-bootstrap-rails

**Comment by yutoJ** [comment]
pagedown-bootstrap-rails これでform作るの調べましたが、使えそうですね！
時間あったら試して、導入できそうだったらview作っちゃいましょうよ！
