### ISSUE TITLE
シードデータを作る

### ISSUE THREAD

**Issue by yutoJ** [yasuhisa1984/dive-23-10#37]
question, answerともそれっぽいのを集めてきたいっすね。

**Comment by yasuhisa1984** [comment]
確かにそれっぽいの欲しいですよね。

Fakerで探して見ましたが、answerで使えそうなのですとFaker::Hacker.say_something_smartとかですかね。
> Faker::Hacker.say_something_smart
 #=> "Try to compress the SQL interface, maybe it will program the back-end hard drive!"

大変そうですけど、スタックオーバーフローのAPIから、
タイトルを取得すると本格っぽくなりそうですね。
http://blog.asial.co.jp/1351

**Comment by yutoJ** [comment]
まさにこれっすね！stack over flow API使い方針にしましょう！
