### ISSUE TITLE
お気に入り追加に失敗したときのエラー文表示

### ISSUE THREAD

**Issue by sayao88** [yasuhisa1984/dive-23-10#66]
リダイレクト先は使い勝手の問題なのであとまわしかも・・？

**Comment by yutoJ** [comment]
現在DBの方で重複をさせないようにしているので不整合は起こらないのですが、たまに1 clickで大量に
requestが発行されることがあり、controllerでinsertと失敗が多く、rollbackしたというlogがあります。

viewから見ると内部がそんなことになっているというのが見えないので、もしかしたらmessage出さないほうがいいかもです、、

試してみてって感じですね、、
