### ISSUE TITLE
質問フォーム作成

### ISSUE THREAD

**Issue by yasuhisa1984** [yasuhisa1984/dive-23-10#8]

**Comment by 46158n** [comment]
質問フォームと#7の質問作成画面って何が違うんでしたっけ。。
こっちはindexにパーシャルで投稿フォームを作る感じなんでしょうか？

**Comment by yasuhisa1984** [comment]
前回の打ち合わせではindexに投稿フォームを作る予定はなかったと思います。
#8は重複しているのでcloseしても良いかもしれませんね。
