### ISSUE TITLE
僕だけ？質問詳細から質問一覧へブラウザの戻るボタンで戻るとなんども読み込む

### ISSUE THREAD

**Issue by yutoJ** [yasuhisa1984/dive-23-10#87]
なぜかわからないのですが、何度も読み込みます。navigationの質問一覧でアクセスすると起こりません。

謎です、、、

**Comment by sayao88** [comment]
同じ現象かわからないのですが、質問一覧にアクセスすると（質問一覧のリンクからでも同様に）何度も読み込む現象がありました。（そうならないときもあるみたいです）

質問一覧画面アクセス時にブラウザの開発者ツールを立ち上げてみると Turbolinksが動いている？ような感じでしたが、私はTurbolinksの機能がよく理解できていません。。（ページ遷移をajaxっぽく行ってくれるもの、でしょうか・・？）

**Comment by sayao88** [comment]
> 質問一覧にアクセスすると（質問一覧のリンクからでも同様に）何度も読み込む現象がありました

質問一覧リンクからも現象が起こると書きましたが、それは読み込み待ちが発生していただけで特に問題なさそうです。
戻るボタンで戻ると、turbolinks-progress-barがいくつも読み込まれて一気に処理が重たくなりました。

**Comment by sayao88** [comment]
turbolinksについていろいろ調べたのですが、結局読み込み時の挙動の原因はわかりませんでした。
「turbolinksをオフにする」というのをやってみたら（下記リンク参照ください）読み込み挙動に問題なかったので、やはりturbolinksが原因だとは思うのですが。
http://qiita.com/kazz187/items/12737363d62b9c91993c

**Comment by yutoJ** [comment]
調査ありがとうございます！

このlinkの対応はうまくいきそうですか？

**Comment by sayao88** [comment]
turbolinksをオフにすることで普通に表示されるようになったので、そのように対応しました（プルリク中）

**Comment by sayao88** [comment]
masterに反映されたのでクローズします。
