### ISSUE TITLE
ユーザー詳細画面がエラーなので修正する、ログアウト時にも見ることができるかどうか検討

### ISSUE THREAD

**Issue by sayao88** [yasuhisa1984/dive-23-10#96]
ユーザー詳細画面がエラーになるようなので修正が必要です。

あとは、ログアウト時にもユーザー詳細を見られるかどうか検討したいです。
※その場合current_userをviewで書いてしまっているので修正が必要かと思います。

**Comment by yutoJ** [comment]
見れる方がいい派です

**Comment by sayao88** [comment]
コメントありがとうございます！
いったんエラーを直しつつ、ログアウト時にも見られるようにしてみます。
